### ISSUE TITLE
what's the version of lm_eval?

### ISSUE THREAD

**Issue by chixu-xmu** [locuslab/wanda#76]
hi, I got a problem here:
`Traceback (most recent call last):                                                                                                                                      
  File "/home/workingplace/xc/exercise/wanda/main.py", line 119, in <module>                                                                                            
    main()                                                                                                                                                              
  File "/home/workingplace/xc/exercise/wanda/main.py", line 108, in main                                                                                                
    results = eval_zero_shot(args.model, model, tokenizer, task_list, num_shot, accelerate)                                                                             
  File "/home/workingplace/xc/exercise/wanda/lib/eval.py", line 134, in eval_zero_shot                                                                                  
    from lm_eval import tasks, evaluator                                                                                                                                
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/lm_eval/__init__.py", line 1, in <module>                                                
    from .evaluator import evaluate, simple_evaluate                                                                                                                    
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/lm_eval/evaluator.py", line 15, in <module>                                              
    import lm_eval.models                                                                                                                                               
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/lm_eval/models/__init__.py", line 1, in <module>                                         
    from . import (                                                                                                                                                     
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/lm_eval/models/hf_vlms.py", line 13, in <module>                                         
    from lm_eval.models.huggingface import HFLM                                                                                                                         
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/lm_eval/models/huggingface.py", line 18, in <module>                                     
    from peft import PeftModel                                                                                                                                          
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/peft/__init__.py", line 22, in <module>                                                  
    from .auto import (                                                                                                                                                 
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/peft/auto.py", line 32, in <module>                                                      
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING                                                                                                               
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/peft/mapping.py", line 25, in <module>                                                   
    from .mixed_model import PeftMixedModel                                                                                                                             
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/peft/mixed_model.py", line 29, in <module>                                               
    from .peft_model import PeftModel                                                                                                                                   
  File "/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/peft/peft_model.py", line 37, in <module>                                                
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel                                                                                  
ImportError: cannot import name 'Cache' from 'transformers' (/home/workingplace/xc/anaconda3/envs/wanda/lib/python3.9/site-packages/transformers/__init__.py)   `
I suppose the version of lm_eval is wrong. I install the 0.4.5 version of lm_eval. Please tell me the right version of lm_eval. I've seen the install.md, readme.md, and all issues that posted, but I haven't seen any solutions. Please help me, thanks!

**Comment by chixu-xmu** [comment]
I have known that I should download the file that author provided.

**Comment by Pengxin-Guo** [comment]
> I have known that I should download the file that author provided.

Hi, could you please clarify which specific file needs to be downloaded?
